### ISSUE TITLE
Wrong endpoint

### ISSUE THREAD

**Issue by pierrehrt** [slimpotatoboy/resend#2]
Hi Dipen,
I posted on your medium article and open issue here is case you don't check medium.

Your package isn't working, I had to check and debug your code, i found out that your not using the right endpoint.
to send email the edpoint is "https://api.resend.com/emails"
and not "[https://api.resend.com/"](https://api.resend.com/emails)

I tried to pull request you but seems you don't allow public contribution.

**Comment by slimpotatoboy** [comment]
The package has been updated!
